on:
  workflow_call:
    inputs:
      build_command:
        required: true
        type: string
      artifacts_publish_command:
        required: false
        type: string
      docker_build_command:
        required: false
        type: string
      docker_ecr_repository:
        required: false
        type: string
      # TODO add to the docs
      ecs_task_definition:
        required: false
        type: string
      ecs_task_definition_container_name:
        required: false
        type: string
      ecs_service:
        required: false
        type: string
      ecs_cluster:
        required: false
        type: string
      slack_channel_id:
        required: false
        type: string
      app_path:
        required: false
        type: string
      app_name:
        required: true
        type: string

    secrets:
      aws_ca_domain:
        description: 'AWS_CA_DOMAIN'
        required: false
      aws_ca_owner_id:
        description: 'AWS_CA_OWNER_ID'
        required: false
      aws_role_to_assume:
        description: 'AWS_ROLE_TO_ASSUME'
        required: false
      aws_env_account_id:
        description: 'AWS_ROLE_TO_ASSUME'
        required: false
      slack_bot_token:
        description: 'SLACK_BOT_TOKEN'
        required: false
      slack_channel_id:
        description: 'SLACK_CHANNEL_ID'
        required: false

jobs:
  Build:
    runs-on: ubuntu-latest

    steps:
      - name: "Setup: Checkout"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: "Setup: Java"
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - name: "Setup: AWS Credentials"
        uses: aws-actions/configure-aws-credentials@v1
        with:
          role-to-assume: ${{ secrets.aws_role_to_assume }}
          aws-region: eu-central-1

      - name: "Setup: AWS ECR login"
        if: ${{ inputs.docker_build_command != 0 }}
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      - name: "Setup: Initialize variables"
        id: vars
        run: |
          codeartifact_token=$(aws codeartifact get-authorization-token --domain ${{ secrets.aws_ca_domain }} --domain-owner ${{ secrets.aws_ca_owner_id }} --query authorizationToken --output text)
          echo "::add-mask::$codeartifact_token"
          echo "::set-output name=codeartifact_auth_token::$codeartifact_token"
          echo "::set-output name=run_url::https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
          echo "::set-output name=ENV_AWS_ACCOUNT_ID::${{ secrets.AWS_ACCOUNT_ID_DEV }}"

      - name: "Setup: Increment version"
        id: version
        uses: paulhatch/semantic-version@v4

      - name: Build
        uses: gradle/gradle-build-action@v2
        with:
          arguments: ${{ inputs.build_command }} -PmavenUser=aws -PmavenPassword=${{ steps.vars.outputs.codeartifact_auth_token }}

      - name: "Build Image: Copy Dockerfile and related into current repository"
        run: |
          git clone --branch feature/AT-333 https://.:${{ secrets.GITHUB_TOKEN }}@github.com/meawallet/meapay-backend-cicd softpos-buildstack

      - name: "Build Image: Set up Docker Buildx"
        uses: docker/setup-buildx-action@v1

      - name: copy file
        uses: canastro/copy-file-action@master
        with:
          source: "app-artifact/${{ inputs.app_name }}-app.jar"
          target: "${{ inputs.app_name }}.jar"

      - name: "Build Image: Docker build java image"
        env:
          service_full_name: softpos-${{ inputs.app_name }}-service
        uses: docker/build-push-action@v2
        with:
          context: .
          build-args: |
            APP_NAME=${{ inputs.app_name }}
            JVM_OPTS="-Xms1024m -Xmx2048m"
          push: false
          tags: ${{ secrets.aws_env_account_id }}.dkr.ecr.eu-central-1.amazonaws.com/${{ env.service_full_name }}:latest

      - name: "Publish: Render Amazon ECS Task Definition"
        if: ${{ inputs.ecs_task_definition != 0 && inputs.ecs_task_definition_container_name != 0 }}
        uses: aws-actions/amazon-ecs-render-task-definition@v1
        with:
          task-definition: ${{ inputs.ecs_task_definition }}
          container-name: ${{ inputs.ecs_task_definition_container_name }}
          image: ${{ steps.publish-docker.outputs.image }}

      - name: "Publish: Create and push tag"
        if: ${{ success() && inputs.build_command != 0 && inputs.artifacts_publish_command != 0 }}
        run: |
          git tag ${{ steps.version.outputs.version_tag }}
          git push origin ${{ steps.version.outputs.version_tag }}

      - name: "Deploy: Amazon ECS DEV"
        if: ${{ inputs.ecs_service != 0 && inputs.ecs_cluster != 0 }}
        uses: aws-actions/amazon-ecs-deploy-task-definition@v1
        with:
          task-definition: ${{ steps.task-def.outputs.task-definition }}
          service: ${{ inputs.ecs_service }}
          cluster: ${{ inputs.ecs_cluster }}
          wait-for-service-stability: true

      - name: "Notify: Slack"
        id: slack
        if: ${{ failure() && inputs.slack_channel_id != 0 }}
        env:
          SLACK_BOT_TOKEN: ${{ secrets.slack_bot_token }}
        uses: slackapi/slack-github-action@v1.18.0
        with:
          channel-id: ${{ inputs.slack_channel_id }}
          slack-message: Pipeline failed ${{ steps.vars.outputs.run_url }}
